### ISSUE TITLE
Suggestion: folders (kind of)

### ISSUE THREAD

**Issue by romu70** [dullage/flatnotes#129]
Still in order to preserve the KISS principle, why not supporting folders from the note title.

For example: if the note title is folder/note, then Flatnotes would create the « folder » folder, with the note file inside. And instead of sorting notes from A to Z, they would be shown top folders first and then child folders and notes.

**Comment by bjuergens** [comment]
as a suggestion to make it even simpler: maybe the "folder"-mechanism is only applied in the GUI. i.e. there is a symbol (maybe "/", or maybe something else like "!"), that the backend completely ignores, but the UI will group these items and puts them in a collapsable div. 

as an additional side note: this could be realized by a custom JS. e.g. when there is a "/custom.js" on the server, it will be added to the index.html.

**Comment by saftl** [comment]
Hi, 
Dendron is doing the same with a "." as separater. works quite good and could be used together on the same folder. For example on desktop with Dendron, on mobile with Flatnotes or so.

**Comment by dullage** [comment]
Thank you for the suggestions all. I appreciate that omitting any kind of folder structure is limiting and opinionated but it's a core design principle for flatnotes. So much so that it's in the name "**flat**notes".

So, as much as I want to take feedback and suggestions on board, I'm afraid I will have to close this one off.
