### ISSUE TITLE
Files with .MD (uppercase) extension are not recognized as markdown files

### ISSUE THREAD

**Issue by flarecentury** [Dullage/flatnotes#50]
Hi,

I have an issue when I use my markdown folder as the 'database' dir. The files with `.MD` extension are not recognized as markdown files. As a result, these files do not show up in the frontend. To show them, I have to change all the files with `.MD` extension to `.md`.

I expect that both `.MD` and `.md` files should be treated as markdown files and show up in the frontend.

Thank you.

**Comment by Dullage** [comment]
Hi. Thank you for raising this. Unfortunately though, this is by design. 

For simplicity I chose to simply assume an extension of lowercase `.md`. If this could vary from note to note then I'd need to keep track of of it all the way through to the front end. This seemed like a lot of work for something that could be solved by sticking to a consistent extension. 

Note: On Linux, `my note.md` and `my note.MD` are two different files. 

I'll add this to the docs in case it catches anyone else out.

**Comment by Dullage** [comment]
README has now been updated to include info about file extensions.

**Comment by clach04** [comment]
> README has now been updated to include info about file extensions.

I can't locate this but there is a wiki FAQ entry https://github.com/dullage/flatnotes/wiki#what-file-extensions-are-supported
