### ISSUE TITLE
Can't use some characters in title

### ISSUE THREAD

**Issue by nealhead** [Dullage/flatnotes#52]
For example, when trying to use ? in a title I receive the following error in the logs:

"POST /api/notes HTTP/1.1" 400 Bad Request

**Comment by Dullage** [comment]
Hey @nealhead 👋. 

Unfortunately this is a limitation of the database-less design. The note titles are used as the file names of the markdown files and as such, cannot use certain characters. 

When creating/renaming a note, the server element of flatnotes will check to ensure that the title doesn't contain any of the following characters: `<>:"/\|?*`. 

This list is mainly driven by Windows requirements (Linux is a lot less stringent). So, as some users may run flatnotes on Windows, these characters are deemed invalid. 

Equally, flatnotes was developed on a Windows machine and even though I run my personal copy on Linux, I then sync my notes to various Windows machines using syncthing. 

What I should do is add better validation warning to the front end (rather than the generic failed to save pop up you probably see). 

I hope this helps explain things.

**Comment by Dullage** [comment]
A friendly message has been added in v2.2.0.
