### ISSUE TITLE
support for authentication only for editing notes

### ISSUE THREAD

**Issue by foxydevloper** [dullage/flatnotes#72]
support for authentication only for adding and deleting notes would be great to allow this to be used as a very minimal blog application

**Comment by pbogre** [comment]
one way i could see this being done is how it's done in [this other project](https://github.com/pldubouilh/gossa/tree/master/support), where there is an option to start the whole program in Read-Only mode, and then you have to setup two different instances of flatnotes where one is read only and the other isn't, and you can choose how to deal with authentication for each instance independently 

i think this solution makes the most sense because it doesn't require a whole new authentication process and it's simply and extra argument to pass when starting the service instead. something like `FLATNOTES_READ_ONLY` in the docker environment.

**Comment by dullage** [comment]
As of v3.2.1, this is now possible.

I took an approach similar to that suggested by @pbogre whereby there is a new `read_only` authentication mode that essentially disables all creation, modification and deletion behaviour both in the frontend and at the API level.

The [Environment Variables wiki article](https://github.com/dullage/flatnotes/wiki/Environment-Variables) explains more.
