### ISSUE TITLE
tag auto-completion and tag overview

### ISSUE THREAD

**Issue by philipp-koch** [dullage/flatnotes#76]
In order to make it easier to use tags consistently, it would help a lot to have

* auto-completion when using tags (be it while writing a note, i.e. typing `#` and then, without a space, any character allowed would bring up a modal-window with a selectable list of tags already in use, or in the search box)
* a list of all tags used and the number of occurrences of the respective tag in all notes as a whole

**Comment by dullage** [comment]
Thanks for the suggestions 👍.

This is similar to #35 on which there has been some progress. There is an `/api/tags` endpoint that returns a list of indexed tags. It doesn't yet support usage counts but that might be a trivial change. 

I did have problems with code comments being recognised as tags but this has now been solved in a recent release.

I like the auto-complete suggestion.

**Comment by philipp-koch** [comment]
Thanks for your reply! I'm looking forward to maybe seeing this implemented some day.

**Comment by dullage** [comment]
A new tag menu has been added and is now available in the pre-release [v5.0.0-rc.1](https://github.com/dullage/flatnotes/releases/tag/v5.0.0-rc.1) 🎉.

**Comment by Limerick-gh** [comment]
Great project! I like the simplicity a lot!!

I like to bring up the initial idea, since I am missing a auto-complete for already used tags, too.
It wold be really great to have the same feature in  note writing like it is already available in the search box.
This would help to keep tagging consistent. 
Entering  a # would simply show up a list of already used tags and the list would get more specfifc, if you start typing right after the #-character.
Thanks a lot in advance for reconsdering.

**Comment by dullage** [comment]
Thanks for the kind comments @Limerick-gh. What you're suggesting is covered by a separate suggestion (see #186). Please go give that a thumbs up to show your interest.

**Comment by Limerick-gh** [comment]
Oh, I missed that. Thanks for directing to the right thread. 😃👍🏻
